### ISSUE TITLE
Full architecture - Supplementary material

### ISSUE THREAD

**Issue by fabienbaradel** [mzolfaghari/ECO-efficient-video-understanding#1]
Hi,
Thanks for making open-source your submission that is very useful. Would it be possible for you to upload the supplementary material on arxiv?
In your paper you refer to the supplementary material concerning the architecture.
I am especially interested in your 2D_Nets_s and 3D_Net architecture.

Thanks and well done for your impressive work :)

Fabien

**Comment by dongzhuoyao** [comment]
same

**Comment by mzolfaghari** [comment]
Hi,

Thanks for your interest on our work. 
We updated paper on Arxiv and attached the supplementary material at the end:
https://arxiv.org/pdf/1804.09066.pdf

Please feel free to ask if you have any question.

Best,

**Comment by fabienbaradel** [comment]
Thanks @mzolfaghari for the update. I will read your supplementary material for sure.
Best,
