### ISSUE TITLE
Using trained PyTorch model

### ISSUE THREAD

**Issue by sophia-wright-blue** [mzolfaghari/ECO-efficient-video-understanding#16]
Hello,

Thank you for making the PyTorch implementation available. What are the steps to using a trained model for activity recognition on some videos in my folder?

I have downloaded the ECO Lite model using gd_download.py and have the model downloaded. I have a folder of videos in .avi format.

Thanks,

**Comment by mzolfaghari** [comment]
@sophia-wright-blue 

To train the model you need to create the training and testing list of your dataset which each folder includes frames of a video.
If you're training on a dataset other than ones we used, then you need also update the code with information of your dataset, e.g. number of classes.
