### ISSUE TITLE
Why is ECO performing so well for early recognition?

### ISSUE THREAD

**Issue by yijunCai** [mzolfaghari/ECO-efficient-video-understanding#2]
Hi @mzolfaghari 
Thanks for your paper and the upcoming code! The performance of ECO is very impressive, especially for the early recognition task. According to your paper, ECO can achived an accuracy of more than 0.8 when the observation ratio is only 0.1. Since ECO is trained with sparse sampling to capture long-term dependencies, I'm wondering why it performs so well for early recognition, in which the input is obtained by dense sampling. Any intuitive idea about that?  By the way, have you tried performing inference by dense sliding window, as typical 3D CNN does?

**Comment by yijunCai** [comment]
Thanks for your reply! I forgot to take the 2D branch into consideration, which may  be the major contribution for early recognition as you commented.  Still I'm very interested in the performance of the 3D branch with dense sampling,  which should be not only much slower but also much lower by intuition. Looking forward to your final version!

**Comment by mzolfaghari** [comment]
Please feel free to reopen it if you had any further question.
