### ISSUE TITLE
Training ECO PyTorch on the Moments in Time dataset

### ISSUE THREAD

**Issue by sophia-wright-blue** [mzolfaghari/ECO-efficient-video-understanding#21]
Hello, I intend to use the ECO PyTorch code to train the model on the moments in time dataset. I have the frames extracted and the training and validation lists prepared.

 I'd greatly appreciate any guidance on the changes to be made to the code (main.py) to train the model on the moments dataset (or any dataset other than kinetics).

Thank you,

**Comment by mzolfaghari** [comment]
You need to add the number of classes and image name format between lines 40-50 in main.py. In addition, add your dataset name (which you used in main.py) to opts.py line 3.
