### ISSUE TITLE
in the file models_ECO_Lite/kinetics/deploy.prototxt  why the input_dim is 80?

### ISSUE THREAD

**Issue by l2009312042** [mzolfaghari/ECO-efficient-video-understanding#27]
name: "ECOLite"
####################################### data #######################################
input: "data"
input_dim: 80

why the input_dim is 80 ?  
is  batchsize  5   ?16 * 5 =80 ,is that right ?

**Comment by mzolfaghari** [comment]
Yes, it's right. You can have any (number*16) depending on your GPU memory.
