### ISSUE TITLE
Train Caffe model on Moments dataset

### ISSUE THREAD

**Issue by sophia-wright-blue** [mzolfaghari/ECO-efficient-video-understanding#30]
I was able to make the changes and train the PyTorch version of ECO on the Moments in Time dataset. Could you please guide me to the changes to be made to train the Caffe version of ECO on the Moments in Time dataset? Thanks,

**Comment by mzolfaghari** [comment]
@sophia-wright-blue Sorry for the late response!. Please let me know if you successfully trained the Caffe version on the Moments in Time dataset. Otherwise, let me know the problem.

Best,

**Comment by sophia-wright-blue** [comment]
thanks for replying @mzolfaghari , i had to move on to a different project, but hope to get back to this one soon, will close this issue for now and reopen when I get to work on this again, thanks for your help, looking forward to more updates from you!
