### ISSUE TITLE
about  "Online video understading",in your paper

### ISSUE THREAD

**Issue by stevve** [mzolfaghari/ECO-efficient-video-understanding#31]
can you show specific implements  of "Online video understading" codes，and by the way,is this alogrithm use in training or testing model?

**Comment by mzolfaghari** [comment]
@stevve We provided the script for "Online action recognition" in this [link](https://github.com/mzolfaghari/ECO-efficient-video-understanding/tree/master/scripts/online_recognition). This algorithm has been used only in the testing time for the online scenario.
