### ISSUE TITLE
About online recognition and video captioning

### ISSUE THREAD

**Issue by UCASUSTC** [mzolfaghari/ECO-efficient-video-understanding#32]
Hi ,I am very interested in your outstanding work.
But I have a problem when i run online recognition.py
I set the model paths in online_recognition.py as :

mean_file = "/home/gs/Desktop/ECO/caffe_3d/action_matlab/rgb_mean.mat"
model_def_file = '/home/gs/Desktop/ECO/Models/ECO_Lite_kinetics.caffemodel'
model_file = '/home/gs/Desktop/ECO/models_ECO_Lite/kinetics/deploy.prototxt'

when i run "python online_recognition.py"
And i got error:

WARNING: Logging before InitGoogleLogging() is written to STDERR
W1224 10:08:03.607410  2554 _caffe.cpp:139] DEPRECATION WARNING - deprecated use of Python interface
W1224 10:08:03.607450  2554 _caffe.cpp:140] Use this instead (with the named "weights" parameter):
W1224 10:08:03.607463  2554 _caffe.cpp:142] Net('/home/gwl/Desktop/test/model/deploy.prototxt', 1, weights='/home/gwl/Desktop/test/model/ECO_Lite_kinetics.caffemodel')
[libprotobuf ERROR google/protobuf/text_format.cc:245] Error parsing text-format caffe.NetParameter: 51:12: Message type "caffe.LayerParameter" has no field named "bn_param".
F1224 10:08:03.625159  2554 upgrade_proto.cpp:90] Check failed: ReadProtoFromTextFile(param_file, param) Failed to parse NetParameter file: /home/gwl/Desktop/test/model/deploy.prototxt
*** Check failure stack trace: ***

Did I set it wrong?
Please help me,thanks!

**Comment by ShynarT** [comment]
Could you, please, tell how you were able to solve the problem?
