### ISSUE TITLE
About video captioning 

### ISSUE THREAD

**Issue by fengluxu** [mzolfaghari/ECO-efficient-video-understanding#34]
Thanks for your excellent repo and paper.
From your paper I learnt that you used kinetic pertained model to extract features for video captioning task. Could you explain more about how you extract ECO features for MSVD dataset? (for instance, from which layer you extract features,  how to set num_class for MSVD dataset)

Thank you in advance.

**Comment by mzolfaghari** [comment]
Hi @fengluxu 

You can extract the features from the "global pool" layer of ECO Lite and last concatenation layer of ECO full. To extract features, you need to write your own script. But if you have time to wait, we'll provide it until the end of the next week. By the way, there is no need for setting num_class! You just need to input the frames and get the features.

Best,
