### ISSUE TITLE
About make && make install

### ISSUE THREAD

**Issue by TwinkleYR** [mzolfaghari/ECO-efficient-video-understanding#35]
I have finished the steps before make && make install,when I conducted make && make install,it had a error about  
No implicit rule found for 'install'.
 Finished prerequisites of target file 'install'.
Must remake target 'install'.
make: *** No rule to make target 'install'。 停止。
Can you help me solve the problem?Thank you in advance

**Comment by mzolfaghari** [comment]
@TwinkleYR Could you please send me a screenshot of your problem? If you don't get any error then It's ready to use.
