### ISSUE TITLE
About the training details

### ISSUE THREAD

**Issue by HuaZheLei** [mzolfaghari/ECO-efficient-video-understanding#38]
@mzolfaghari Thank you for your excellent work. Your paper mentioned that 

> We initialize the weights of the 2D-Net weights with the BN-Inception architecture [31] pre-trained on Kinetics, as provided by [33].

> 

I wonder how you train a 2D-Net on Kinetics.

**Comment by mzolfaghari** [comment]
@HuaZheLei it's almost similar to the 3D network but we will have score fusion at the final layer to get a single score for each video. To check the details of our 2D network architecture please have look on [BN-inception ](https://github.com/mzolfaghari/ECO-efficient-video-understanding/blob/master/models_ECO_Lite/kinetics/bn_inception_kinetics_rgb_pretrained/bn_inception_rgb_deploy.prototxt) network definition.
