### ISSUE TITLE
Some questions about dataset file list.

### ISSUE THREAD

**Issue by wzmsltw** [mzolfaghari/ECO-efficient-video-understanding#4]
Hi @mzolfaghari 

Thanks for your excellent work! In updated repo, I found that the dataset file lists are not provided (kinetics_train_frm.txt  for example). Can you provide these files for reference? Thanks so much!

**Comment by mzolfaghari** [comment]
Hi @wzmsltw 

You can find the corresponding list in the '''data_list''' folder.
Please feel free to reopen the issue if you had any problem.
