### ISSUE TITLE
About the blob's problem when I run online_recognition?

### ISSUE THREAD

**Issue by idealboy** [mzolfaghari/ECO-efficient-video-understanding#40]
sir,

when I run online_recognition.py , when loading the model, the problem occurs such below:

 blob.hpp:141] Check failed: num_axes() <= 4 (5 vs. 4) Cannot use legacy accessors on Blobs with > 4 axes

does the caffe_3d branch support C3D?

thank you very much!

And I just compile caffe by make$make pycaffe but not cmake.

**Comment by idealboy** [comment]
It seems that I must compile with cuDNN supporting, then the blob will be compatible with the 5 dimension tensor

**Comment by mzolfaghari** [comment]
@idealboy Happy to hear that you solved the problem.
Closing now. Feel free to re-open it if you had any problem.
