### ISSUE TITLE
About the inference speed?

### ISSUE THREAD

**Issue by idealboy** [mzolfaghari/ECO-efficient-video-understanding#41]
Dear sir,

I just ust the online_recognition.py method to test the speed, and I found that I wiil use about 50ms for one forward with input shape(16*3*224*224),

I think I can't achieve the hight VPS in the paper, thank you !

**Comment by idealboy** [comment]
And I use volta 100

**Comment by mzolfaghari** [comment]
@idealboy As explained in the paper, you should not consider data I/O in the time calculation and only calculate pure network processing time.
