### ISSUE TITLE
download pretrained models

### ISSUE THREAD

**Issue by jesszgc** [mzolfaghari/ECO-efficient-video-understanding#44]
nice work in video understanding, i am very intrested in your work. 
as google is blocked in China, i can not download the pretrained models you uploaded to google driver. so,  can you share you pretrained models by Baidu Yun for us. thanks a lot

**Comment by mzolfaghari** [comment]
@jesszgc which models you want? Caffe models or PyTorch?

**Comment by mzolfaghari** [comment]
I provided Caffe pre-trained models on UCF101 and HMDB51 in the following link:
https://freiburg958.sharefile.com/d-s3508c7f3a7440dfa

**Comment by huaze555** [comment]
@mzolfaghari hello，thanks for your cool works, I want to train my data on FULL kinetics model, can you share the ECO_Lite_kinetics.caffemodel url by BAIDU Yun ?  thank you very much!

**Comment by huaze555** [comment]
@mzolfaghari waiting for your reply
