### ISSUE TITLE
2D tensor changed to 3D tensor, runtime error 

### ISSUE THREAD

**Issue by ZealACMer** [mzolfaghari/ECO-efficient-video-understanding#45]
I tried to change 2D tensor into 3D tensor, so it can be feed into 3D Conv. The code are shown as follows:
y = self.con1x1(x) # 2D tensor
y = y.view((-1, 96, 16) + y.size()[2:]) #2D tensor changed to 3D tensor

error:
![image](https://user-images.githubusercontent.com/16794553/60673778-23479200-9eab-11e9-8410-11fc7cc44a7b.png)
Thank you so much for you kind help.

**Comment by mzolfaghari** [comment]
@ZealACMer Are you sure that the number of samples is 16? 3161088 is not equal to batch*96*16*28*28. I  think it's better to check the shape of "y" after 2D tensor and figure out the problem. Let me know if you still didn't find the problem.
