### ISSUE TITLE
Download links to pre-trained models

### ISSUE THREAD

**Issue by vnigade** [mzolfaghari/ECO-efficient-video-understanding#46]
Hi @mzolfaghari,

Thanks for sharing your code!

I tried to download the pre-trained ECO_(full|Lite)_UCF101.caffemodel but I couldn't. Similarly, I couldn't download pre-trained models on HMDB51.
e.g.
Download id: 1FMFjtzt_sBWRUyBV86d1cuwHAlnw7HpB
https://docs.google.com/uc?export=download&id=1FMFjtzt_sBWRUyBV86d1cuwHAlnw7HpB

If possible, could you please check and share the correct download ids?

Thanks!

**Comment by mzolfaghari** [comment]
@vnigade I check the links and seems that some of them are not valid anymore. I've provided pre-trained models on UCF101 and HMDB51 again in the following link:
https://drive.google.com/open?id=1gWInNekKJmiSsqUn0_w0pc329mh4zekM

Please let me know if you had any problem.
