### ISSUE TITLE
the uncertainties about the file "online_recognition.py"

### ISSUE THREAD

**Issue by wasahaiah** [mzolfaghari/ECO-efficient-video-understanding#48]
Firstly thank your great contribution. I have a  question about the testing.
when test the .caffemodel "ECOfull_UCF101_16F.caffemodel", with the input of validation video, .e.g., "v_PlayingDhol_g04_c02.avi", the result changes sevaral times, but, I find there no correct labels. I have test a lot of times with other vailidation video, the conclution seems not to be changed. 

can you give me some suggestion about testing ? Thank you very much

**Comment by wasahaiah** [comment]
I have solved the problem. The deploy file should be rectified.

**Comment by wasahaiah** [comment]
I have solved the problem. The deploy file should be rectified(name: "fc8N" to  name: "fc8u").

**Comment by dklee98** [comment]
Hello @wasahaiah 

I’m the original author/maintainer of TRG-Planner. I noticed your repository is a fork of the original project.

I previously sent you an email (via your contact email: [wangnzhou@sina.com](mailto:wangnzhou@sina.com)) regarding an urgent and important matter related to this repository, but I haven’t heard back yet.
Could you please check it and reply when you get a chance?

In addition, I’ve opened a pull request on your repository related to this matter (https://github.com/wasahaiah/TRG-planner)
When you have time, I would appreciate it if you could also take a look at the PR and let me know your thoughts.

If your email is not available, please let me know other contact information.
You can also reach me at: [dklee@urobotics.ai](mailto:dklee@urobotics.ai)

Thank you for your time and cooperation.
