### ISSUE TITLE
change the network to Fully Convolutional Networks(FCN) different output

### ISSUE THREAD

**Issue by jesszgc** [mzolfaghari/ECO-efficient-video-understanding#50]
great work for action recongnition.
i am trying to change your network to FCN to fit big scene with multi actions.
change the input from 224*224 to 512*512 we got 100*51 output with the kinetcs model.
with total black input the 100 output of 1*51 differs from the same output as we expected.
can you help me with this problem?
bad english writing, hope you can understand my word.
looking for your reply.

**Comment by mzolfaghari** [comment]
@jesszgc If you increase the input size, you need to change the size of pooling layer to get prober output. Unfortunately, I didn't understand your problem very well. Maybe you could elaborate it more with example.

**Comment by jesszgc** [comment]
thanks for your reply.
for the Full model, change the input size to 512x512, and "r2Dto3D" layer to shape { dim: -1 dim: 16 dim: 96 dim: 64 dim: 64 } , without anyother modification we can get the output size of 100x51.
i am expecting the 100x51 to reshape to the 10x10x51 to demostrate the heatmap of the inputdata.
with total black inputdata (every pixel is(0,0,0)), we expect the output to be simple(each of the 10x10 is the same) while they are totally different.
looking for your reply.

**Comment by mzolfaghari** [comment]
@jesszgc If I understand it correctly, you're giving input data of all zeros and expecting an output of same numbers. I guess that's normal to get different output for the black inputdata. You have a fully connected layer at the end which initialized randomly and therefore still could give different output for the zero input. In the ECOFull, we have two fully connected layers.
