### ISSUE TITLE
 I have some questions about the speed of I3D to ask you.

### ISSUE THREAD

**Issue by Jiangchitang** [mzolfaghari/ECO-efficient-video-understanding#51]
Dear author, I am fortunate to read your thesis. I have some questions about the speed of recognition to ask you.
The speed of I3D in your paper is only 0.9 clip/s.  but the speed I tested reached 40 clip/s ( Titan V). 
Is the method we tested different? I hope to know more details.

**Comment by mzolfaghari** [comment]
@Jiangchitang The reported speed is the speed of video inference "Number of complete videos evaluated by the model". To calculate this you need to consider augmentations of video and splitting it to clips. By clipping and augmentations, the speed decreases to the number we've reported. Of course, if you consider only a single clip and just center cropping the speed will be much higher.

**Comment by Jiangchitang** [comment]
Thinks!
