### ISSUE TITLE
about the weight sharing of architecture overview of ECO or ECOLite

### ISSUE THREAD

**Issue by Ai-is-light** [mzolfaghari/ECO-efficient-video-understanding#6]
@mzolfaghari 
Thanks for your excellent idea, paper and repo. And, after reading your paper, I'm a little bit confused about the weight sharing in your architecture overview. Would you mind telling me more details about it. I thought the N frames are related to the N number of Inception_3c of 2D-Net, so what's the meaning about the weight sharing.
Thanks.
Looking forward to any replies.

**Comment by mzolfaghari** [comment]
Hi @Ai-is-light,

Actually, we have only one instance of Inception_3c of 2D Net and each single frame pass through this network. In the paper with weight sharing, we meant that all N frames use the same 2D Net. If you check the model definition, you'll find that we stacked N frames and reshaped the input to have these N frames in the form of a batch. For example, If we have 4 frames and batch size is 32, then input to the 2D Net will have a batch size of 128.

**Comment by mzolfaghari** [comment]
Please feel free to re-open the issue if you had further questions.
