### ISSUE TITLE
about the video_data_param and train.txt

### ISSUE THREAD

**Issue by Ai-is-light** [mzolfaghari/ECO-efficient-video-understanding#7]
@mzolfaghari 
Thanks for your excellent repo and paper.
video_data_param {
    source: ".../train.txt"
    batch_size: 16
    new_length: 1
    new_width: 320
    new_height: 240
    num_segments: 16
    modality: RGB
    shuffle: true
    name_pattern: "%05d.jpg"
  }

I want to use your model to train my custom datasets, so, would you mind telling us the format in your train.txt. And, what's more, as for the num_segments: 16,  there are 16 
   {mean_value: [104]
    mean_value: [117]
    mean_value: [123]
}
the number of the num_segments is the same as the {mean_value}?

**Comment by mzolfaghari** [comment]
Hi @Ai-is-light ,

Format for the data list is like this:
`/path_to_data_folder/  number_of_frames  action_label`

First column path to the data folder, the second column shows the number of frames for each video and last column is the label of action.

**Comment by mzolfaghari** [comment]
``
