### ISSUE TITLE
how to set multi-GPUs

### ISSUE THREAD

**Issue by Ai-is-light** [mzolfaghari/ECO-efficient-video-understanding#9]
when I train the network, I got the information as following:
(I build the caffe-training environment under the  https://github.com/yjxiong/temporal-segment-networks)
You are running caffe compiled with MPI support. Now it's running in non-parallel model
what's meaning?

What's more, I can't use the multi-gpus to train my model.

Looking forward to any advice.

**Comment by Ai-is-light** [comment]
@mzolfaghari would you mind supporting your caffe docker images?
Thanks

**Comment by Ai-is-light** [comment]
@mzolfaghari Thanks, I also set the 'iter_size' for increasing the batch size.

**Comment by sophia-wright-blue** [comment]
Hello, 

Thank you for making the code available - I have a follow-up on your PyTorch comment - is there a scheduled release date for the PyTorch version?

Thanks,

**Comment by mzolfaghari** [comment]
Hi @sophia-wright-blue 

The code will be available next week.

**Comment by sophia-wright-blue** [comment]
That's awesome - looking forward to learning more about your model.
